### ISSUE TITLE
Fails to start on Windows 10

### ISSUE THREAD

**Issue by dalebaldwin** [faceyspacey/redux-first-router-boilerplate#11]
````
Listening @ http://localhost:3000/
{ Error: invalid argument
    at pathToArray (C:\Users\[username]\Documents\Personal Projects\redux-first-router-boilerplate\node_modules\memory-fs\lib\MemoryFileSystem.js:44:10)
    at MemoryFileSystem.writeFileSync (C:\Users\[username]\Documents\Personal Projects\redux-first-router-boilerplate\node_modules\memory-fs\lib\MemoryFileSystem.js:200:13)
    at C:\Users\[username]\Documents\Personal Projects\redux-first-router-boilerplate\node_modules\autodll-webpack-plugin\lib\createMemory.js:62:11
    at runCallback (timers.js:800:20)
    at tryOnImmediate (timers.js:762:5)
    at processImmediate [as _immediateCallback] (timers.js:733:5)
From previous event:
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:528:3)
  code: 'EINVAL',
  errno: 18,
  message: 'invalid argument',
  path: '\\assets\\vendor.js' }
````
Just went to get my dev setup running on my Win10 machine and discovered that yarn start fails with the above error. My app and the boilerplate work on my Mac fine so guessing this is something windows related.

**Comment by faceyspacey** [comment]
hmmm, it looks like it could be the autodll package. removing that and trying without it may bare some results.

**Comment by dalebaldwin** [comment]
Yeah that was it, found the issue in their issue cue. Can be fixed by upgrading the package version to 0.3.4.
